"""Initial schema

Revision ID: 7d5efcf508ba
Revises: 
Create Date: 2026-07-08 14:16:16.260551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5efcf508ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'NURSE', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('mfaSecret', sa.String(length=64), nullable=True),
    sa.Column('isMfaEnabled', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('logId', sa.UUID(), nullable=False),
    sa.Column('performedByUserId', sa.UUID(), nullable=True),
    sa.Column('actionType', sa.Enum('READ_PHI', 'WRITE_PHI', 'AUTH_LOGIN', 'DATA_EXPORT', name='audit_action_type'), nullable=False),
    sa.Column('targetRecordId', sa.UUID(), nullable=False),
    sa.Column('targetTable', sa.String(length=100), nullable=False),
    sa.Column('ipAddress', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performedByUserId'], ['users.userId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('logId')
    )
    op.create_table('doctor_profiles',
    sa.Column('doctorId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=150), nullable=False),
    sa.Column('licenseNumber', sa.String(length=100), nullable=False),
    sa.Column('departmentId', sa.UUID(), nullable=True),
    sa.Column('consultationFee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availabilityStatus', sa.Enum('AVAILABLE', 'ON_LEAVE', 'IN_SURGERY', name='availability_status'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctorId'),
    sa.UniqueConstraint('licenseNumber'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('patient_profiles',
    sa.Column('patientId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender'), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('emergencyContactName', sa.String(length=150), nullable=False),
    sa.Column('emergencyContactPhone', sa.String(length=20), nullable=False),
    sa.Column('bloodType', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='blood_type'), nullable=False),
    sa.Column('encryptedNationalId', sa.String(length=512), nullable=False),
    sa.Column('insuranceProvider', sa.String(length=150), nullable=True),
    sa.Column('insurancePolicyNumber', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patientId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('appointments',
    sa.Column('appointmentId', sa.UUID(), nullable=False),
    sa.Column('patientId', sa.UUID(), nullable=False),
    sa.Column('doctorId', sa.UUID(), nullable=False),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointmentType', sa.Enum('IN_PERSON', 'TELEHEALTH', 'FOLLOW_UP', name='appointment_type'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('reasonForVisit', sa.Text(), nullable=False),
    sa.Column('telehealthRoomId', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.doctorId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.patientId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointmentId')
    )
    op.create_table('clinical_encounters',
    sa.Column('encounterId', sa.UUID(), nullable=False),
    sa.Column('appointmentId', sa.UUID(), nullable=False),
    sa.Column('patientId', sa.UUID(), nullable=False),
    sa.Column('doctorId', sa.UUID(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('clinicalNotes', sa.Text(), nullable=False),
    sa.Column('icd10Code', sa.String(length=10), nullable=False),
    sa.Column('prescriptionData', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encryptedDiagnosisText', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appointmentId'], ['appointments.appointmentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.doctorId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.patientId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('encounterId'),
    sa.UniqueConstraint('appointmentId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_encounters')
    op.drop_table('appointments')
    op.drop_table('patient_profiles')
    op.drop_table('doctor_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
