"""Add pharmacy, nurse, reception: prescriptions, vitals, patient assignment

Revision ID: 9be910d7d63c
Revises: 7d5efcf508ba
Create Date: 2026-07-10 09:43:35.114798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be910d7d63c'
down_revision: Union[str, None] = '7d5efcf508ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_signs',
    sa.Column('vitalId', sa.UUID(), nullable=False),
    sa.Column('patientId', sa.UUID(), nullable=False),
    sa.Column('nurseId', sa.UUID(), nullable=True),
    sa.Column('bloodPressureSystolic', sa.Integer(), nullable=False),
    sa.Column('bloodPressureDiastolic', sa.Integer(), nullable=False),
    sa.Column('heartRate', sa.Integer(), nullable=False),
    sa.Column('temperatureCelsius', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('respiratoryRate', sa.Integer(), nullable=False),
    sa.Column('oxygenSaturation', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recordedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nurseId'], ['users.userId'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.patientId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vitalId')
    )
    op.create_table('prescriptions',
    sa.Column('prescriptionId', sa.UUID(), nullable=False),
    sa.Column('encounterId', sa.UUID(), nullable=False),
    sa.Column('patientId', sa.UUID(), nullable=False),
    sa.Column('doctorId', sa.UUID(), nullable=False),
    sa.Column('medicationName', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('durationDays', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', name='prescription_status'), nullable=False),
    sa.Column('fulfilledByUserId', sa.UUID(), nullable=True),
    sa.Column('fulfilledAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prescribedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctor_profiles.doctorId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounterId'], ['clinical_encounters.encounterId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fulfilledByUserId'], ['users.userId'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patientId'], ['patient_profiles.patientId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescriptionId')
    )
    op.add_column('patient_profiles', sa.Column('assignedNurseId', sa.UUID(), nullable=True))
    op.add_column('patient_profiles', sa.Column('assignedDoctorId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patient_profiles', 'users', ['assignedDoctorId'], ['userId'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['assignedNurseId'], ['userId'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.drop_column('patient_profiles', 'assignedDoctorId')
    op.drop_column('patient_profiles', 'assignedNurseId')
    op.drop_table('prescriptions')
    op.drop_table('vital_signs')
    # ### end Alembic commands ###
